#+Title: Skript zur Prüfung zum 4. Dan
#+Author: Göran Kirchner
#+Language: de

* Prüfungsprogramm

** Prüfungsschwerpunkte

Ab dem 4. Dan soll die Beschäftigung mit der Theorie der Sportart intensiviert werden.
Die langjährige Erfahrung, die gesteigerten Kenntnisse und die daraus entstehende Kreativität sollen in dieser Stufe zum Ausdruck kommen und möglichst auch an andere weitergegeben werden.

** Vorkenntnisse 

Alle Techniken der Kyu‐ und Dan‐ Ausbildungsstufen (außer Kata) können stichprobenartig abgeprüft werden.

Es können alle Techniken des bisherigen Ausbildungsprogramms (außer Kata) im Sinne
einer Ergebnis‐ und Qualitätssicherung stichprobenartig abgeprüft werden.

** Standtechnik (stichprobenartig)

Erläuterung der folgenden Wurfprinzipien und Demonstration mit je 2 Techniken aus je 2 sinnvollen Situationen:
- Sicheln
- Fegen
- Blockieren / Stoppen
- Verwringen
- Einhängen
- Eindrehen
- Ausheben
- Einrollen
- Selbstfallen

Die oben aufgeführten Wurfprinzipien sollen anhand von jeweils zwei unterschiedlichen Wurftechniken aus jeweils zwei unterschiedlichen, judotypischen, sinnvollen Situationen erläutert und demonstriert werden (nähere Erläuterungen zu den Wurfprinzipien im Begleitskript).

Der Prüfling muss sich auf alle Prinzipien vorbereiten, die Prüfungskommission soll 2‐3
Beispiele auswählen, um den Zeitrahmen nicht zu sprengen.

** Bodentechnik (stichprobenartig)

Demonstration, Erläuterung und Begründung grundsätzlicher Verhaltensweisen, Prinzipien und Lösungsmöglichkeiten am Boden:
a) Angriff aus Ober‐ und Unterlage
b) Abwehr aus Ober‐ und Unterlage
jeweils zu allen Standardsituationen.

Grundsätzliche Verhaltensweisen am Boden, wie /Angriffs‐ und Verteidigungsverhalten/,
sowie realistische Lösungsmöglichkeiten gegen alle Standardsituationen müssen
erläutert, begründet und ausführlich demonstriert werden können. Dies gilt für das
Angriffs‐ und auch für das Verteidigungsverhalten, sowohl in Ober‐ als auch in
Unterlage. Zu unseren *Standardsituationen* des Bodenkampfes gehören:
- die Bauchlage
- die Bankposition
- die Rückenlage (Angriff zwischen den Beinen)
- die Beinklammer (ein Bein ist geklammert, einfach oder doppelt)

Der Prüfling muss sich auf alle Standardsituationen vorbereiten, die
Prüfungskommission soll 2‐3 Beispiele auswählen um den Zeitrahmen nicht zu sprengen.

** Theorie 

Geschichtliche Entwicklung und die Judo‐Prinzipien.

Der Prüfling soll die historische Entwicklung des Judo von den Ursprüngen in Japan bis
zur Gegenwart in Deutschland skizzieren können.

Er soll die Bedeutung von Jigoro Kano und die von ihm entwickelten Prinzipien,
*Seiryoku‐zen‐yo* und *Ji‐ta‐kyo‐ei*, kurz beschreiben und bewerten.

** Kata 

Wahlweise *Kodokan‐goshin‐jutsu* oder *Ju‐no‐kata*.

* Vorkenntnisse

* Standtechnik

* Bodentechnik

* Theorie

** Geschichte

** Jigoro Kano

** Seiryoku‐zen‐yo (das technische Prinzip) [精力善用]

Das erste Prinzip beschreibt, wie man die Judotechniken ausführen soll und wie man sich im Kampf zu verhalten hat. Es kann mit *"Bester Einsatz von Geist und Körper"* oder "Bester Einsatz der vorhande
nen Kräfte" umschrieben werden und beinhaltet eine deutliche Absage an das 'Kraftmeiertum', die bloße Anwendung schierer physischer Kraft. Mit diesem Prinzip will Kano den Begriff *Ju* ("sanft, nachgeben, geschmeidig") des Wortes Judo näher charakterisieren. Die Idee des Siegens durch Nachgeben, sowohl als körperliche Eigenschaft als auch als geistig-emotionale Einstellung findet sich hier wieder. 

In der Judo-Praxis können folgende theoretisch-taktischen Grundsätze diesem Prinzip zugeordnet werden: 
- Ausnutzen der Bewegung des Gegners und des eigenen Schwungs 
- Anwenden der Hebelgesetze 
- Brechen des gegnerischen Gleichgewichts 
- das eigene Gewicht mehr einsetzen als die eigene Kraft 
- auch bei aggressiven Handlungen des Gegners kühlen Kopf bewahren 
- den Gegner studieren und Schwachpunkte nutzen 
- die eigenen Stärken gegen die Schwächen des Gegners nutzen 

[[http://kodokanjudoinstitute.org/en/doctrine/word/seiryoku-zenyo/][kodokanjudoinstitute]]

** Ji‐ta‐kyo‐ei (das moralische Prinzip) [自他共栄]

Das zweite Prinzip Jigoro Kanos hebt Judo über eine bloße Zweikampfsportart hinaus und lässt es zum Erziehungssystem werden. In der Übersetzung kann man dieses Prinzip als *"Gegenseitige Hilfe für den wechselseitigen Fortschritt und das beiderseitige Wohlergehen"* verstehen. Kano macht damit deutlich, mit welcher Einstellung und Haltung man Judo erlernen und betreiben soll. Er macht klar, dass der Partner nicht nur "Übungsobjekt" ist, jemand, an dem man übt, sondern ein Gegenüber, für das man Verantwortung entwickeln muss und für dessen Fortschritt in technischer und persönlicher Hinsicht man genauso arbeiten muss, wie für den eigenen. Ohne willig mitarbeitende Partner ist ein Judo-Studium nicht möglich. Mit dem Prinzip des gegenseitigen Helfens und Verstehens hat Kano den Aspekt des *Do* ("Weg, Prinzip, Grundsatz") des Wortes Judo als Lebensweg oder prinzipielle Einstellung zum Leben im Miteinander näher beschrieben. 

Auf der Judo-Matte beim täglichen Training kann man die Anwendung dieses Prinzips unter andere
m daran erkennen, dass 
- Tori die Kontrolle über die Fallübung von Uke ausübt 
- Uke bei Würge- und/oder Hebeltechniken rechtzeitig abschlägt und Tori die Technik daraufhin sofort beendet 
- alle Übenden miteinander trainieren und kein Partner zum Üben abgelehnt wird 
- beim Üben von Judotechniken und beim Randori Rücksicht auf Alter, Geschlecht, körperliche und technische  Entwicklung des Partners genommen wird und wechselseitige Erfolgserlebnisse ermöglicht werden 
- jeder Übende bereit ist, für sein Handeln und für die Gruppe Verantwortung zu übernehmen. 

** Onore o tsukushite naru o matsu! [尽己竢成]

#+BEGIN_QUOTE
「己を尽して成るを竢つ」
#+END_QUOTE

Do Your Best and Await the Result.


* Kata


